-- ====================================================================
-- Namaste Siam Indian Kitchen — Production PostgreSQL / Supabase Schema
-- Migration Draft: Initial Schema Generation
-- Generated: 2026-06-15
-- ====================================================================

-- Enable UUID extension for robust, secure random ID strings
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ====================================================================
-- ====================================================================
-- 1. TABLE: categories
-- ====================================================================
CREATE TABLE IF NOT EXISTS categories (
    id VARCHAR(50) PRIMARY KEY, -- acts as unique category key
    slug VARCHAR(100) UNIQUE NOT NULL, -- SEO-friendly identifier (e.g. 'starters', 'thai-specials')
    name VARCHAR(100) NOT NULL UNIQUE, -- category name
    label VARCHAR(100) NOT NULL DEFAULT '', -- legacy mapping
    display_order INT NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0, -- legacy sort
    active BOOLEAN NOT NULL DEFAULT true,
    is_visible BOOLEAN NOT NULL DEFAULT true, -- legacy mapping
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index is added to accelerate default category ordering fetches
CREATE INDEX IF NOT EXISTS idx_categories_display_order ON categories (display_order);
CREATE INDEX IF NOT EXISTS idx_categories_slug ON categories (slug);

-- ====================================================================
-- 2. TABLE: foods (Dishes & Beverages Catalogue)
-- ====================================================================
CREATE TABLE IF NOT EXISTS foods (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(255) UNIQUE NOT NULL, -- SEO-friendly identifier (e.g. 'tom-yum-soup')
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    price_thb NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    category_id VARCHAR(50) NOT NULL,
    veg BOOLEAN NOT NULL DEFAULT true,
    food_type VARCHAR(20) NOT NULL CHECK (food_type IN ('veg', 'nonveg')) DEFAULT 'veg', -- legacy mapping
    spice_level VARCHAR(50) NOT NULL DEFAULT '🌶 Mild',
    ingredients VARCHAR(100)[] NOT NULL DEFAULT '{}',
    chef_special BOOLEAN NOT NULL DEFAULT false,
    bestseller BOOLEAN NOT NULL DEFAULT false, -- popular dish
    popular BOOLEAN NOT NULL DEFAULT false, -- maps to bestseller
    customer_favorite BOOLEAN NOT NULL DEFAULT false,
    today_special BOOLEAN NOT NULL DEFAULT false,
    image_url TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    is_available BOOLEAN NOT NULL DEFAULT true, -- legacy mapping
    display_order INT NOT NULL DEFAULT 0,
    display_order_today INT NOT NULL DEFAULT 0,
    display_order_chef INT NOT NULL DEFAULT 0,
    display_order_popular INT NOT NULL DEFAULT 0,
    display_order_favorite INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign key constraint with cascading updates to handle potential slug refactoring
    CONSTRAINT fk_foods_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
        
    -- Constraint enforcing that prices must be greater than or equal to zero
    CONSTRAINT chk_positive_price
        CHECK (price_thb >= 0)
);

-- Indexes for lightning fast lookups, categories grouping, filtering and full text search queries
CREATE INDEX IF NOT EXISTS idx_foods_category_id ON foods (category_id);
CREATE INDEX IF NOT EXISTS idx_foods_filters ON foods (active, today_special, chef_special, bestseller, customer_favorite);
CREATE INDEX IF NOT EXISTS idx_foods_slug ON foods (slug);
CREATE INDEX IF NOT EXISTS idx_foods_name_trgm ON foods USING gin (to_tsvector('english', name));

-- ====================================================================
-- 3. TABLE: restaurant_info
-- ====================================================================
CREATE TABLE IF NOT EXISTS restaurant_info (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    address TEXT NOT NULL,
    phone VARCHAR(100) NOT NULL,
    opening_hours VARCHAR(255) NOT NULL,
    instagram VARCHAR(100) NOT NULL DEFAULT '',
    website VARCHAR(100) NOT NULL DEFAULT '',
    dining_style VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ====================================================================
-- 4. TABLE: about_info
-- ====================================================================
CREATE TABLE IF NOT EXISTS about_info (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    story_paragraphs TEXT[] NOT NULL DEFAULT '{}',
    highlights TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ====================================================================
-- 5. TABLE: gallery
-- ====================================================================
CREATE TABLE IF NOT EXISTS gallery (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title VARCHAR(255) NOT NULL DEFAULT '', -- photography title/alt text
    alt_text VARCHAR(255) NOT NULL DEFAULT '', -- legacy mapping
    image_url TEXT NOT NULL,
    is_tall BOOLEAN NOT NULL DEFAULT false, -- structural rendering flag
    display_order INT NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0, -- legacy sort
    active BOOLEAN NOT NULL DEFAULT true,
    is_visible BOOLEAN NOT NULL DEFAULT true, -- legacy mapping
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_gallery_sort_order ON gallery (sort_order);
CREATE INDEX IF NOT EXISTS idx_gallery_display_order ON gallery (display_order);

-- ====================================================================
-- 6. TABLE: chat_settings (WhatsApp & LINE Integration)
-- ====================================================================
CREATE TABLE IF NOT EXISTS chat_settings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    whatsapp_number VARCHAR(100) NOT NULL DEFAULT '',
    whatsapp_default_message TEXT NOT NULL DEFAULT '',
    line_id VARCHAR(100) NOT NULL DEFAULT '',
    line_qr_url TEXT NOT NULL DEFAULT '',
    contact_active_channel VARCHAR(50) NOT NULL DEFAULT 'both', -- 'whatsapp', 'line', 'both', 'disabled'
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ====================================================================
-- MODULE: TRIGGER AUTO-UPDATE FOR "updated_at" TIMESTAMP COLUMNS
-- ====================================================================
CREATE OR REPLACE FUNCTION update_timestamp_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Attach timestamp triggers helper to keep trace records automatically consistent
CREATE TRIGGER trg_categories_update BEFORE UPDATE ON categories FOR EACH ROW EXECUTE PROCEDURE update_timestamp_column();
CREATE TRIGGER trg_foods_update BEFORE UPDATE ON foods FOR EACH ROW EXECUTE PROCEDURE update_timestamp_column();
CREATE TRIGGER trg_restaurant_info_update BEFORE UPDATE ON restaurant_info FOR EACH ROW EXECUTE PROCEDURE update_timestamp_column();
CREATE TRIGGER trg_about_info_update BEFORE UPDATE ON about_info FOR EACH ROW EXECUTE PROCEDURE update_timestamp_column();
CREATE TRIGGER trg_gallery_update BEFORE UPDATE ON gallery FOR EACH ROW EXECUTE PROCEDURE update_timestamp_column();
CREATE TRIGGER trg_chat_settings_update BEFORE UPDATE ON chat_settings FOR EACH ROW EXECUTE PROCEDURE update_timestamp_column();


-- ====================================================================
-- MODULE: SECURITY & ROW LEVEL SECURITY (RLS) POLICIES
-- ====================================================================

-- 1. Enable Row-Level Security globally across all tables
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE foods ENABLE ROW LEVEL SECURITY;
ALTER TABLE restaurant_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE about_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_settings ENABLE ROW LEVEL SECURITY;

-- 2. Define PUBLIC READ (SELECT) access guidelines for all users
CREATE POLICY "Allow public SELECT reads for categories" ON categories FOR SELECT TO public USING (active = true);
CREATE POLICY "Allow public SELECT reads for foods" ON foods FOR SELECT TO public USING (active = true);
CREATE POLICY "Allow public SELECT reads for restaurant_info" ON restaurant_info FOR SELECT TO public USING (true);
CREATE POLICY "Allow public SELECT reads for about_info" ON about_info FOR SELECT TO public USING (true);
CREATE POLICY "Allow public SELECT reads for gallery" ON gallery FOR SELECT TO public USING (active = true);
CREATE POLICY "Allow public SELECT reads for chat_settings" ON chat_settings FOR SELECT TO public USING (is_active = true);

-- 3. Define AUTHENTICATED ADMIN WRITE (INSERT, UPDATE, DELETE) permission policies (Using Supabase Auth auth.role())
CREATE POLICY "Allow authenticated admin write edits on categories"
    ON categories FOR ALL TO authenticated
    USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated admin write edits on foods"
    ON foods FOR ALL TO authenticated
    USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated admin write edits on restaurant_info"
    ON restaurant_info FOR ALL TO authenticated
    USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated admin write edits on about_info"
    ON about_info FOR ALL TO authenticated
    USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated admin write edits on gallery"
    ON gallery FOR ALL TO authenticated
    USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated admin write edits on chat_settings"
    ON chat_settings FOR ALL TO authenticated
    USING (true) WITH CHECK (true);


-- ====================================================================
-- SEED DATA (To match initial static template records perfectly on setup)
-- ====================================================================

-- ====================================================================
-- SEED DATA (To match initial static template records perfectly on setup)
-- ====================================================================

INSERT INTO categories (id, slug, name, label, sort_order, display_order, active, is_visible) VALUES
('starters', 'starters', 'Starters', 'Starters', 1, 1, true, true),
('soups', 'soups', 'Soups', 'Soups', 2, 2, true, true),
('salads', 'salads', 'Salads', 'Salads', 3, 3, true, true),
('thai', 'thai-specials', 'Thai Specials', 'Thai Specials', 4, 4, true, true),
('indian', 'indian', 'Indian', 'Indian', 5, 5, true, true),
('chinese', 'chinese', 'Chinese', 'Chinese', 6, 6, true, true),
('main', 'main-course', 'Main Course', 'Main Course', 7, 7, true, true),
('rice', 'rice', 'Rice', 'Rice', 8, 8, true, true),
('noodles', 'noodles', 'Noodles', 'Noodles', 9, 9, true, true),
('pizza', 'pizza', 'Pizza', 'Pizza', 10, 10, true, true),
('burger', 'burger', 'Burger', 'Burger', 11, 11, true, true),
('desserts', 'desserts', 'Desserts', 'Desserts', 12, 12, true, true),
('beverages', 'beverages', 'Beverages', 'Beverages', 13, 13, true, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO foods (slug, name, description, price_thb, category_id, veg, food_type, spice_level, ingredients, chef_special, bestseller, popular, customer_favorite, today_special, image_url, display_order, display_order_today, display_order_chef, display_order_popular, display_order_favorite, active, is_available) VALUES
('tom-yum-soup', 'Tom Yum Soup', 'Aromatic Thai soup with lemongrass, galangal, and mushrooms.', 299.00, 'soups', true, 'veg', '🌶🌶 Medium', ARRAY['Lemongrass','Galangal','Mushroom','Lime Leaves'], true, true, true, true, true, 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1000&q=80', 1, 1, 1, 1, 1, true, true),
('paneer-tikka', 'Paneer Tikka', 'Char-grilled cottage cheese with smoky spices and mint.', 349.00, 'starters', true, 'veg', '🌶🌶 Medium', ARRAY['Paneer','Yogurt','Capsicum','Onion'], true, false, false, false, false, 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=1000&q=80', 2, 2, 2, 2, 2, true, true),
('chicken-satay', 'Chicken Satay', 'Skewered chicken with rich peanut glaze.', 389.00, 'starters', false, 'nonveg', '🌶 Mild', ARRAY['Chicken','Peanut','Garlic','Soy'], false, true, true, true, false, 'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=1000&q=80', 3, 3, 3, 3, 3, true, true),
('green-thai-curry', 'Green Thai Curry', 'Coconut curry with fresh basil and seasonal vegetables.', 429.00, 'thai', true, 'veg', '🌶🌶🌶 Hot', ARRAY['Coconut Milk','Thai Basil','Broccoli','Zucchini'], true, true, true, true, false, 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1000&q=80', 4, 4, 4, 4, 4, true, true),
('butter-chicken', 'Butter Chicken', 'Classic creamy tomato gravy with tender chicken.', 459.00, 'indian', false, 'nonveg', '🌶🌶 Medium', ARRAY['Chicken','Tomato','Butter','Cream'], true, true, true, true, false, 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=1000&q=80', 5, 5, 5, 5, 5, true, true),
('veg-hakka-noodles', 'Veg Hakka Noodles', 'Wok-tossed noodles with crisp vegetables.', 289.00, 'noodles', true, 'veg', '🌶 Mild', ARRAY['Noodles','Capsicum','Carrot','Cabbage'], false, true, true, false, false, 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=1000&q=80', 6, 6, 6, 6, 6, true, true),
('margherita-pizza', 'Margherita Pizza', 'Stone-baked pizza with mozzarella, basil, and olive oil.', 399.00, 'pizza', true, 'veg', '🌶 Mild', ARRAY['Mozzarella','Basil','Tomato','Olive Oil'], false, true, true, true, false, 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1000&q=80', 7, 7, 7, 7, 7, true, true),
('truffle-mushroom-burger', 'Truffle Mushroom Burger', 'Juicy patty with truffle mayo and caramelized onions.', 379.00, 'burger', false, 'nonveg', '🌶 Mild', ARRAY['Patty','Brioche','Mushroom','Truffle Mayo'], true, false, false, false, false, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1000&q=80', 8, 8, 8, 8, 8, true, true),
('thai-mango-salad', 'Thai Mango Salad', 'Refreshing salad with raw mango and herbs.', 249.00, 'salads', true, 'veg', '🌶🌶 Medium', ARRAY['Raw Mango','Peanut','Mint','Lime'], false, false, false, false, false, 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1000&q=80', 9, 9, 9, 9, 9, true, true),
('jeera-rice', 'Jeera Rice', 'Fragrant basmati tossed with cumin and ghee.', 199.00, 'rice', true, 'veg', '🌶 Mild', ARRAY['Basmati','Cumin','Ghee'], false, false, false, false, false, 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=1000&q=80', 10, 10, 10, 10, 10, true, true),
('chocolate-mousse', 'Chocolate Mousse', 'Velvety dark chocolate mousse with cocoa dust.', 229.00, 'desserts', true, 'veg', '🌶 Mild', ARRAY['Dark Chocolate','Cream','Cocoa'], false, true, true, true, false, 'https://images.unsplash.com/photo-1579954115563-e72bf1381629?auto=format&fit=crop&w=1000&q=80', 11, 11, 11, 11, 11, true, true),
('saffron-lassi', 'Saffron Lassi', 'Chilled yogurt drink infused with saffron.', 179.00, 'beverages', true, 'veg', '🌶 Mild', ARRAY['Yogurt','Saffron','Cardamom'], false, false, false, false, false, 'https://images.unsplash.com/photo-1628207776546-365bb710ee93?auto=format&fit=crop&w=1000&q=80', 12, 12, 12, 12, 12, true, true);

INSERT INTO restaurant_info (name, address, phone, opening_hours, instagram, website, dining_style) VALUES
('Namaste Siam Indian Kitchen', '456 Flavor Street, Bangkok 10110, Thailand', '+66-2-123-4567', 'Monday – Sunday: 11:00 AM – 11:00 PM', '@namastesiam', 'www.namastesiam.com', 'Premium Casual • Family • Fine Taste');

INSERT INTO about_info (story_paragraphs, highlights) VALUES
(
    ARRAY[
        'At Namaste Siam Indian Kitchen, every plate tells a story of heritage, craftsmanship, and passion. Our kitchen celebrates authentic recipes with a contemporary touch, using handpicked produce, premium spices, and balanced flavors that feel both soulful and refined.',
        'From timeless classics to chef-curated specialties, our menu is designed for guests who appreciate quality, consistency, and unforgettable taste.'
    ],
    ARRAY[
        '🥬 Fresh ingredients sourced daily',
        '📜 Authentic recipes with modern finesse',
        '👨‍🍳 Passionate chefs, crafted presentations',
        '✨ Premium quality in every serving'
    ]
);

INSERT INTO gallery (image_url, title, alt_text, is_tall, sort_order, display_order, active, is_visible) VALUES
('https://images.unsplash.com/photo-1528605105345-5344ea20e269?auto=format&fit=crop&w=1200&q=80', 'Restaurant interior', 'Restaurant interior', true, 1, 1, true, true),
('https://images.unsplash.com/photo-1541544181074-e9b7f47eb4f6?auto=format&fit=crop&w=1200&q=80', 'Food plating', 'Food plating', false, 2, 2, true, true),
('https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80', 'Dining table', 'Dining table', false, 3, 3, true, true),
('https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80', 'Chef at work', 'Chef at work', false, 4, 4, true, true),
('https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80', 'Kitchen', 'Kitchen', false, 5, 5, true, true);

INSERT INTO chat_settings (whatsapp_number, whatsapp_default_message, line_id, line_qr_url, contact_active_channel, is_active) VALUES
('+6621234567', 'Hello, I would like to book a table at Namaste Siam!', 'namastesiam_line', 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://line.me/R/ti/p/~namastesiam_line', 'both', true);
