import { Dish, Category, RestaurantInfo, AboutInfo, GalleryItem } from './types';

export const RESTAURANT_INFO: RestaurantInfo = {
  name: "Namaste Siam Indian Kitchen",
  address: "456 Flavor Street, Bangkok 10110, Thailand",
  phone: "+66-2-123-4567",
  openingHours: "Monday – Sunday: 11:00 AM – 11:00 PM",
  instagram: "@namastesiam",
  website: "www.namastesiam.com",
  diningStyle: "Premium Casual • Family • Fine Taste",
  whatsappNumber: "+6621234567",
  whatsappMessage: "Hello, I would like to book a table at Namaste Siam!",
  lineId: "namastesiam_line",
  lineQrUrl: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://line.me/R/ti/p/~namastesiam_line",
  contactActiveChannel: "both"
};

export const ABOUT_INFO: AboutInfo = {
  story: [
    "At Namaste Siam Indian Kitchen, every plate tells a story of heritage, craftsmanship, and passion. Our kitchen celebrates authentic recipes with a contemporary touch, using handpicked produce, premium spices, and balanced flavors that feel both soulful and refined.",
    "From timeless classics to chef-curated specialties, our menu is designed for guests who appreciate quality, consistency, and unforgettable taste."
  ],
  highlights: [
    "🥬 Fresh ingredients sourced daily",
    "📜 Authentic recipes with modern finesse",
    "👨‍🍳 Passionate chefs, crafted presentations",
    "✨ Premium quality in every serving"
  ]
};

export const CATEGORIES: Category[] = [
  { id: "all", slug: "all", name: "All", label: "All", display_order: 0, active: true },
  { id: "appetizers", slug: "appetizers", name: "Appetizers", label: "Appetizers", display_order: 1, active: true },
  { id: "soups", slug: "soups", name: "Soups", label: "Soups", display_order: 2, active: true },
  { id: "salads", slug: "salads", name: "Salads", label: "Salads", display_order: 3, active: true },
  { id: "thai", slug: "thai-specials", name: "Thai Specials", label: "Thai Specials", display_order: 4, active: true },
  { id: "indian", slug: "indian", name: "Indian", label: "Indian", display_order: 5, active: true },
  { id: "chinese", slug: "chinese", name: "Chinese", label: "Chinese", display_order: 6, active: true },
  { id: "main", slug: "main-course", name: "Main Course", label: "Main Course", display_order: 7, active: true },
  { id: "rice", slug: "rice", name: "Rice", label: "Rice", display_order: 8, active: true },
  { id: "noodles", slug: "noodles", name: "Noodles", label: "Noodles", display_order: 9, active: true },
  { id: "pizza", slug: "pizza", name: "Pizza", label: "Pizza", display_order: 10, active: true },
  { id: "burger", slug: "burger", name: "Burger", label: "Burger", display_order: 11, active: true },
  { id: "desserts", slug: "desserts", name: "Desserts", label: "Desserts", display_order: 12, active: true },
  { id: "beverages", slug: "beverages", name: "Beverages", label: "Beverages", display_order: 13, active: true }
];

export const DISHES: Dish[] = [
  {
    id: 1,
    slug: "tom-yum-soup",
    name: "Tom Yum Soup",
    description: "Aromatic Thai soup with lemongrass, galangal, and mushrooms.",
    priceTHB: 299,
    category: "soups",
    type: "veg",
    veg: true,
    spiceLevel: "🌶🌶 Medium",
    ingredients: ["Lemongrass", "Galangal", "Mushroom", "Lime Leaves"],
    chefSpecial: true,
    bestseller: true,
    popular: true,
    customerFavorite: true,
    todaySpecial: true,
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1000&q=80",
    display_order: 1,
    display_order_today: 1,
    display_order_chef: 1,
    display_order_popular: 1,
    display_order_favorite: 1,
    active: true
  },
  {
    id: 2,
    slug: "paneer-tikka",
    name: "Paneer Tikka",
    description: "Char-grilled cottage cheese with smoky spices and mint.",
    priceTHB: 349,
    category: "appetizers",
    type: "veg",
    veg: true,
    spiceLevel: "🌶🌶 Medium",
    ingredients: ["Paneer", "Yogurt", "Capsicum", "Onion"],
    chefSpecial: true,
    bestseller: false,
    popular: false,
    customerFavorite: false,
    todaySpecial: false,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=1000&q=80",
    display_order: 2,
    display_order_today: 2,
    display_order_chef: 2,
    display_order_popular: 2,
    display_order_favorite: 2,
    active: true
  },
  {
    id: 3,
    slug: "chicken-satay",
    name: "Chicken Satay",
    description: "Skewered chicken with rich peanut glaze.",
    priceTHB: 389,
    category: "appetizers",
    type: "nonveg",
    veg: false,
    spiceLevel: "🌶 Mild",
    ingredients: ["Chicken", "Peanut", "Garlic", "Soy"],
    chefSpecial: false,
    bestseller: true,
    popular: true,
    customerFavorite: true,
    todaySpecial: false,
    image: "https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=1000&q=80",
    display_order: 3,
    display_order_today: 3,
    display_order_chef: 3,
    display_order_popular: 3,
    display_order_favorite: 3,
    active: true
  },
  {
    id: 4,
    slug: "green-thai-curry",
    name: "Green Thai Curry",
    description: "Coconut curry with fresh basil and seasonal vegetables.",
    priceTHB: 429,
    category: "thai",
    type: "veg",
    veg: true,
    spiceLevel: "🌶🌶🌶 Hot",
    ingredients: ["Coconut Milk", "Thai Basil", "Broccoli", "Zucchini"],
    chefSpecial: true,
    bestseller: true,
    popular: true,
    customerFavorite: true,
    todaySpecial: false,
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1000&q=80",
    display_order: 4,
    display_order_today: 4,
    display_order_chef: 4,
    display_order_popular: 4,
    display_order_favorite: 4,
    active: true
  },
  {
    id: 5,
    slug: "butter-chicken",
    name: "Butter Chicken",
    description: "Classic creamy tomato gravy with tender chicken.",
    priceTHB: 459,
    category: "indian",
    type: "nonveg",
    veg: false,
    spiceLevel: "🌶🌶 Medium",
    ingredients: ["Chicken", "Tomato", "Butter", "Cream"],
    chefSpecial: true,
    bestseller: true,
    popular: true,
    customerFavorite: true,
    todaySpecial: false,
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=1000&q=80",
    display_order: 5,
    display_order_today: 5,
    display_order_chef: 5,
    display_order_popular: 5,
    display_order_favorite: 5,
    active: true
  },
  {
    id: 6,
    slug: "veg-hakka-noodles",
    name: "Veg Hakka Noodles",
    description: "Wok-tossed noodles with crisp vegetables.",
    priceTHB: 289,
    category: "noodles",
    type: "veg",
    veg: true,
    spiceLevel: "🌶 Mild",
    ingredients: ["Noodles", "Capsicum", "Carrot", "Cabbage"],
    chefSpecial: false,
    bestseller: true,
    popular: true,
    customerFavorite: false,
    todaySpecial: false,
    image: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=1000&q=80",
    display_order: 6,
    display_order_today: 6,
    display_order_chef: 6,
    display_order_popular: 6,
    display_order_favorite: 6,
    active: true
  },
  {
    id: 7,
    slug: "margherita-pizza",
    name: "Margherita Pizza",
    description: "Stone-baked pizza with mozzarella, basil, and olive oil.",
    priceTHB: 399,
    category: "pizza",
    type: "veg",
    veg: true,
    spiceLevel: "🌶 Mild",
    ingredients: ["Mozzarella", "Basil", "Tomato", "Olive Oil"],
    chefSpecial: false,
    bestseller: true,
    popular: true,
    customerFavorite: true,
    todaySpecial: false,
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1000&q=80",
    display_order: 7,
    display_order_today: 7,
    display_order_chef: 7,
    display_order_popular: 7,
    display_order_favorite: 7,
    active: true
  },
  {
    id: 8,
    slug: "truffle-mushroom-burger",
    name: "Truffle Mushroom Burger",
    description: "Juicy patty with truffle mayo and caramelized onions.",
    priceTHB: 379,
    category: "burger",
    type: "nonveg",
    veg: false,
    spiceLevel: "🌶 Mild",
    ingredients: ["Patty", "Brioche", "Mushroom", "Truffle Mayo"],
    chefSpecial: true,
    bestseller: false,
    popular: false,
    customerFavorite: false,
    todaySpecial: false,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1000&q=80",
    display_order: 8,
    display_order_today: 8,
    display_order_chef: 8,
    display_order_popular: 8,
    display_order_favorite: 8,
    active: true
  },
  {
    id: 9,
    slug: "thai-mango-salad",
    name: "Thai Mango Salad",
    description: "Refreshing salad with raw mango and herbs.",
    priceTHB: 249,
    category: "salads",
    type: "veg",
    veg: true,
    spiceLevel: "🌶🌶 Medium",
    ingredients: ["Raw Mango", "Peanut", "Mint", "Lime"],
    chefSpecial: false,
    bestseller: false,
    popular: false,
    customerFavorite: false,
    todaySpecial: false,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1000&q=80",
    display_order: 9,
    display_order_today: 9,
    display_order_chef: 9,
    display_order_popular: 9,
    display_order_favorite: 9,
    active: true
  },
  {
    id: 10,
    slug: "jeera-rice",
    name: "Jeera Rice",
    description: "Fragrant basmati tossed with cumin and ghee.",
    priceTHB: 199,
    category: "rice",
    type: "veg",
    veg: true,
    spiceLevel: "🌶 Mild",
    ingredients: ["Basmati", "Cumin", "Ghee"],
    chefSpecial: false,
    bestseller: false,
    popular: false,
    customerFavorite: false,
    todaySpecial: false,
    image: "https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=1000&q=80",
    display_order: 10,
    display_order_today: 10,
    display_order_chef: 10,
    display_order_popular: 10,
    display_order_favorite: 10,
    active: true
  },
  {
    id: 11,
    slug: "chocolate-mousse",
    name: "Chocolate Mousse",
    description: "Velvety dark chocolate mousse with cocoa dust.",
    priceTHB: 229,
    category: "desserts",
    type: "veg",
    veg: true,
    spiceLevel: "🌶 Mild",
    ingredients: ["Dark Chocolate", "Cream", "Cocoa"],
    chefSpecial: false,
    bestseller: true,
    popular: true,
    customerFavorite: true,
    todaySpecial: false,
    image: "https://images.unsplash.com/photo-1579954115563-e72bf1381629?auto=format&fit=crop&w=1000&q=80",
    display_order: 11,
    display_order_today: 11,
    display_order_chef: 11,
    display_order_popular: 11,
    display_order_favorite: 11,
    active: true
  },
  {
    id: 12,
    slug: "saffron-lassi",
    name: "Saffron Lassi",
    description: "Chilled yogurt drink infused with saffron.",
    priceTHB: 179,
    category: "beverages",
    type: "veg",
    veg: true,
    spiceLevel: "🌶 Mild",
    ingredients: ["Yogurt", "Saffron", "Cardamom"],
    chefSpecial: false,
    bestseller: false,
    popular: false,
    customerFavorite: false,
    todaySpecial: false,
    image: "https://images.unsplash.com/photo-1628207776546-365bb710ee93?auto=format&fit=crop&w=1000&q=80",
    display_order: 12,
    display_order_today: 12,
    display_order_chef: 12,
    display_order_popular: 12,
    display_order_favorite: 12,
    active: true
  }
];

export const GALLERY: GalleryItem[] = [
  { id: "1", title: "Restaurant interior", image: "https://images.unsplash.com/photo-1528605105345-5344ea20e269?auto=format&fit=crop&w=1200&q=80", alt: "Restaurant interior", tall: true, display_order: 1, active: true },
  { id: "2", title: "Food plating", image: "https://images.unsplash.com/photo-1541544181074-e9b7f47eb4f6?auto=format&fit=crop&w=1200&q=80", alt: "Food plating", tall: false, display_order: 2, active: true },
  { id: "3", title: "Dining table", image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80", alt: "Dining table", tall: false, display_order: 3, active: true },
  { id: "4", title: "Chef at work", image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80", alt: "Chef at work", tall: false, display_order: 4, active: true },
  { id: "5", title: "Kitchen", image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80", alt: "Kitchen", tall: false, display_order: 5, active: true }
];
